version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    volumes:
      - "./data/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  wp:
    container_name: wp
    depends_on:
      - mysql
    build:
      context: .
      args:
        wp_version: 4.5.2
    links:
      - mysql
    ports:
      - "80:80"
    volumes:
      - "./wordpress:/var/www/html"
  wp-cli:
    container_name: wp-cli
    image: wpack_wp:latest
    depends_on:
      - wp
    links:
      - mysql
    entrypoint: wp
    command: --info
    environment:
      WP_CLI_CONFIG_PATH: /etc/wp-cli/4.5.2.yml
