version: "2"
services:
  db:
    image: mysql:5.6
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
  wordpress:
    build:
      context: ./wordpress
    depends_on:
      - db
    links:
      - db
    volumes:
      - "./wordpress/etc:/etc/wordpress"
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: root
      WP_CLI_CONFIG_PATH: /etc/wordpress/wp-cli.yml
