version: "2"
services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  composer:
    image: composer
    volumes_from:
      - wp
    working_dir: /usr/src/theme
  wp-cli:
    image: tatemz/wp-cli
    depends_on:
      - mysql
    links:
      - mysql
    volumes_from:
      - wp
    volumes:
      - ./wp-cli.yml:/usr/etc/wp-cli.yml
    environment:
      WP_CLI_CONFIG_PATH: /usr/etc/wp-cli.yml
    user: www-data
    entrypoint:
      - wp-cli.phar
    command:
      - --info
  wp:
    image: wordpress
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./theme:/usr/src/theme
      - ./wordpress:/var/www/html
    entrypoint:
      - apache2-foreground
  node:
    image: node:7.4.0-alpine
    user: node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: [npm, run, start]
    ports:
      - 30000:30000
volumes:
  mysql:
