version: "2"
services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  wp:
    image: wordpress
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./theme:/usr/src/theme
      - ./wordpress:/var/www/html
    entrypoint:
      - apache2-foreground
  wp-cli:
    image: tatemz/wp-cli
    depends_on:
      - mysql
    links:
      - mysql
    volumes_from:
      - wp
    volumes:
      - ./wp-cli.yml:/usr/etc/wp-cli.yml
    environment:
      WP_CLI_CONFIG_PATH: /usr/etc/wp-cli.yml
    user: www-data
    entrypoint:
      - wp-cli.phar
    command:
      - --info

volumes:
  mysql:
