version: "2"
volumes:
  mysql:
services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  wp-cli:
    image: tatemz/wp-cli:latest
    depends_on:
      - mysql
    links:
      - mysql
    volumes_from:
      - wordpress
    volumes:
      - ./wp-cli.yml:/usr/etc/wp-cli.yml
    environment:
      WP_CLI_CONFIG_PATH: /usr/etc/wp-cli.yml
    user: www-data
    entrypoint:
      - wp-cli.phar
    command:
      - --info

  wordpress:
    image: wordpress:4.7.1-php5.6-apache
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - .:/usr/src/theme
      - ./wordpress:/var/www/html
    entrypoint:
      - apache2-foreground

  node:
    image: node:7.4.0
    user: node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: [npm, run, start]
    ports:
      - 30000:30000



  # capistrano:
  #   image: ruby:2.4.0-alpine
  #   volumes:
  #     - .:/usr/src/app
  #     - ./vendor_ruby:/usr/local/bundle
  #   working_dir: /usr/src/app
